# Generated by Django 4.2.3 on 2023-07-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
